### PR TITLE
Move to TerminalParsedSentence event

### PR DESCRIPTION
**Pull request by kohanis**
Migrated to .net sdk, target changed to `netstandard2.1`, algorithm changed to `TerminalParsedSentence` event and scan on demand
It also now ignores enemies that can't be scanned (such as girl)
Btw, `RoundManager.SpawnedEnemies`  can't be used - `RoundManager` is basically host only

### CODE REVIEW

**Comment by ManindraDeMel** [comment]
Oh wow thank you for opening this PR

**Comment by ManindraDeMel** [comment]
Does this resolve issue #3? I originally searched for enemyAIs without the use of roundmanager but it didnt work..

**Review by ManindraDeMel — APPROVED** [review]
This looks good good to merge. I will probably merge this in tomorrow after testing it. On another note, i will probably build on this to make the mod more customisable with what enemies can and can't be scanned as well as features discussed in #7. Again, thank you for your contribution!

**Comment by ManindraDeMel** [comment]
Just tested, this does not resolve #3

**Comment by kohanis** [comment]
> Just tested, this does not resolve #3

How exactly was it tested? Literally played with my crew with my version and everything worked
The problem was in the first place in the use of `RoundManager` methods hooks. They fire only for host

**Comment by ManindraDeMel** [comment]
> > Just tested, this does not resolve #3
> 
> How exactly was it tested? Literally played with my crew with my version and everything worked
> The problem was in the first place in the use of `RoundManager` methods hooks. They fire only for host

I just opened a lobby with a friend and tried running the command, i could scan and see enemies whereas my friend couldnt scan and see the same enemies

**Comment by kohanis** [comment]
Well, I don't know what to say to that. Just did 5 days to 11 pm and both reading were identical every time

**Comment by ManindraDeMel** [comment]
> Well, I don't know what to say to that. Just did 5 days to 11 pm and both reading were identical every time

Did you test this as the host or as the client?

**Comment by kohanis** [comment]
Both. I used 2 clients on same machine in lan mode. Netcode is same for enemies

**Comment by ManindraDeMel** [comment]
> Both. I used 2 clients on same machine in lan mode. Netcode is same for enemies

Could you try online? I tested with online with a friend and it didn't seem to work..

**Comment by ManindraDeMel** [comment]
Ok All good. I will still release this as it may work for some. Thanks

**Comment by kohanis** [comment]
Checked online - same result.
I'm not insisting, however I don't see how it can fail to work. A trivial question - does your friend have terminalapi installed?
This approach literally processes all existing EnemyAI's at the time command is executed

**Comment by ManindraDeMel** [comment]
Yes both clients had terminalAPI and the mod installed. I apologize and understand your frustration, but maybe it's on my end then.

**Comment by ManindraDeMel** [comment]
As i mentioned before i will still deploy your work to thunderstore.io today. And test it through r2modman

**Comment by ManindraDeMel** [comment]
Could you send me your compiled DLL through discord? add me @299792458

**Pull request merged**
